import { useState, useEffect, useCallback } from 'react';
import { Search, Eye, CheckCircle, UserCheck } from 'lucide-react';
import { alertsApi, usersApi } from '../services/api';
import { useAuth } from '../hooks/useAuth';
import type { Alert, User, PaginatedResponse } from '../types';

export default function Alerts() {
  const [data, setData] = useState<PaginatedResponse<Alert> | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [filter, setFilter] = useState({ severity: '', status: '' });
  const [search, setSearch] = useState('');
  const [selectedAlert, setSelectedAlert] = useState<Alert | null>(null);
  const { user } = useAuth();

  const fetchAlerts = useCallback(async () => {
    setLoading(true);
    try {
      const params: any = { page, limit: 15 };
      if (filter.severity) params.severity = filter.severity;
      if (filter.status) params.status = filter.status;
      const res = await alertsApi.getAll(params);
      setData(res.data);
    } catch (err) {
      console.error('Failed to fetch alerts', err);
    } finally {
      setLoading(false);
    }
  }, [page, filter]);

  useEffect(() => { fetchAlerts(); }, [fetchAlerts]);

  useEffect(() => {
    if (user?.role === 'ADMIN') {
      usersApi.getAll().then(res => setUsers(res.data)).catch(() => {});
    }
  }, [user]);

  const handleStatusChange = async (id: number, status: string) => {
    await alertsApi.update(id, { status });
    fetchAlerts();
    setSelectedAlert(null);
  };

  const handleAssign = async (id: number, userId: number) => {
    await alertsApi.update(id, { assignedTo: userId });
    fetchAlerts();
  };

  const getSeverityBadge = (s: string) => {
    const cls = s === 'CRITICAL' ? 'badge-critical' : s === 'HIGH' ? 'badge-high' : s === 'MEDIUM' ? 'badge-medium' : 'badge-low';
    return <span className={cls}>{s}</span>;
  };

  const getStatusBadge = (s: string) => {
    const cls = s === 'OPEN' ? 'badge-open' : s === 'INVESTIGATING' ? 'badge-investigating' : 'badge-resolved';
    return <span className={cls}>{s}</span>;
  };

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold">Alerts</h1>
        <p className="text-soc-400 text-sm mt-1">Security alerts generated by detection rules</p>
      </div>

      <div className="flex items-center gap-3">
        <div className="relative flex-1 max-w-md">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-soc-400" />
          <input
            type="text"
            placeholder="Search alerts..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="input-field pl-10"
          />
        </div>
        <select
          value={filter.severity}
          onChange={(e) => { setFilter(f => ({ ...f, severity: e.target.value })); setPage(1); }}
          className="select-field text-sm w-32"
        >
          <option value="">All Severity</option>
          <option value="CRITICAL">Critical</option>
          <option value="HIGH">High</option>
          <option value="MEDIUM">Medium</option>
          <option value="LOW">Low</option>
        </select>
        <select
          value={filter.status}
          onChange={(e) => { setFilter(f => ({ ...f, status: e.target.value })); setPage(1); }}
          className="select-field text-sm w-36"
        >
          <option value="">All Status</option>
          <option value="OPEN">Open</option>
          <option value="INVESTIGATING">Investigating</option>
          <option value="RESOLVED">Resolved</option>
        </select>
      </div>

      <div className="grid gap-3">
        {loading ? (
          <div className="text-center py-8 text-soc-400">Loading...</div>
        ) : data?.data.length === 0 ? (
          <div className="text-center py-8 text-soc-400">No alerts found</div>
        ) : (
          data?.data.map((alert) => (
            <div key={alert.id} className="card hover:bg-soc-700/50 transition-colors">
              <div className="flex items-start justify-between">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    {getSeverityBadge(alert.severity)}
                    {getStatusBadge(alert.status)}
                    {alert.assigned && (
                      <span className="text-xs text-soc-500">
                        Assigned to: {alert.assigned.fullname}
                      </span>
                    )}
                  </div>
                  <h3 className="font-medium text-soc-100">{alert.title}</h3>
                  <p className="text-sm text-soc-400 mt-1">{alert.description}</p>
                  <div className="flex items-center gap-4 mt-2 text-xs text-soc-500">
                    <span>{new Date(alert.createdAt).toLocaleString()}</span>
                    {alert.log && <span>IP: {alert.log.sourceIp}</span>}
                  </div>
                </div>
                <div className="flex items-center gap-2 ml-4">
                  <button
                    onClick={() => setSelectedAlert(alert)}
                    className="p-2 text-soc-400 hover:text-soc-100 hover:bg-soc-700 rounded-lg transition-colors"
                    title="View Details"
                  >
                    <Eye className="w-4 h-4" />
                  </button>
                  {(user?.role === 'ADMIN' || user?.role === 'ANALYST') && alert.status !== 'RESOLVED' && (
                    <>
                      <button
                        onClick={() => handleStatusChange(alert.id, 'RESOLVED')}
                        className="p-2 text-soc-400 hover:text-emerald-400 hover:bg-soc-700 rounded-lg transition-colors"
                        title="Resolve"
                      >
                        <CheckCircle className="w-4 h-4" />
                      </button>
                      {user?.role === 'ADMIN' && (
                        <div className="relative group">
                          <button className="p-2 text-soc-400 hover:text-soc-100 hover:bg-soc-700 rounded-lg transition-colors">
                            <UserCheck className="w-4 h-4" />
                          </button>
                          <div className="absolute right-0 top-full mt-1 bg-soc-700 border border-soc-600 rounded-lg shadow-xl z-10 hidden group-hover:block min-w-[160px]">
                            {users.map(u => (
                              <button
                                key={u.id}
                                onClick={() => handleAssign(alert.id, u.id)}
                                className="block w-full text-left px-3 py-2 text-sm text-soc-300 hover:bg-soc-600"
                              >
                                {u.fullname}
                              </button>
                            ))}
                          </div>
                        </div>
                      )}
                    </>
                  )}
                </div>
              </div>
            </div>
          ))
        )}
      </div>

      {data && data.totalPages > 1 && (
        <div className="flex items-center justify-between">
          <span className="text-sm text-soc-400">Page {page} of {data.totalPages}</span>
          <div className="flex gap-2">
            <button onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1} className="btn-secondary text-sm disabled:opacity-50">Previous</button>
            <button onClick={() => setPage(p => Math.min(data.totalPages, p + 1))} disabled={page === data.totalPages} className="btn-secondary text-sm disabled:opacity-50">Next</button>
          </div>
        </div>
      )}

      {selectedAlert && (
        <div className="fixed inset-0 bg-black/60 flex items-center justify-center z-50" onClick={() => setSelectedAlert(null)}>
          <div className="bg-soc-800 border border-soc-700 rounded-xl p-6 max-w-lg w-full mx-4" onClick={e => e.stopPropagation()}>
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold">Alert Details</h2>
              <button onClick={() => setSelectedAlert(null)} className="text-soc-400 hover:text-soc-100">&times;</button>
            </div>
            <div className="space-y-3">
              <div>
                <span className="text-xs text-soc-400">Title</span>
                <p className="text-sm">{selectedAlert.title}</p>
              </div>
              <div>
                <span className="text-xs text-soc-400">Description</span>
                <p className="text-sm">{selectedAlert.description}</p>
              </div>
              <div className="flex gap-4">
                <div>
                  <span className="text-xs text-soc-400">Severity</span>
                  <p>{getSeverityBadge(selectedAlert.severity)}</p>
                </div>
                <div>
                  <span className="text-xs text-soc-400">Status</span>
                  <p>{getStatusBadge(selectedAlert.status)}</p>
                </div>
              </div>
              {selectedAlert.log && (
                <>
                  <div>
                    <span className="text-xs text-soc-400">Source IP</span>
                    <p className="text-sm font-mono">{selectedAlert.log.sourceIp}</p>
                  </div>
                  <div>
                    <span className="text-xs text-soc-400">Event Type</span>
                    <p className="text-sm">{selectedAlert.log.eventType.replace(/_/g, ' ')}</p>
                  </div>
                </>
              )}
            </div>
            <div className="flex gap-2 mt-6">
              {selectedAlert.status === 'OPEN' && (
                <button onClick={() => handleStatusChange(selectedAlert.id, 'INVESTIGATING')} className="btn-primary text-sm flex-1">Start Investigation</button>
              )}
              {selectedAlert.status === 'INVESTIGATING' && (
                <button onClick={() => handleStatusChange(selectedAlert.id, 'RESOLVED')} className="btn-primary text-sm flex-1">Resolve Alert</button>
              )}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
